language: node_js
node_js:
- '8'
sudo: required
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIVUU5MY5BGECDCPQ
  secret_access_key:
    secure: "YAOwEqOWXkM1KX2X7QA7P9PC1YRtEFb9JUccOwi8XAY4Afq+DrkmbKrCm2vTTz5b3e6myCB85K7DJcJij8uoZjyur8wjyISj2dB+KQP6tvDUUGKiht7Vw4JKg4ffOpfKLvo19mUYaQaIbgn3pvdeAv8BH243FKpagBqu1rWhIjXm62GfSBncA2Jx3c0GhxTOXQmiRmuD98fHToMk0xOpFrQ2BXg2LtoO5eLeGlgqcSyBtx2PUp9Wdz1yVXi0rdhPD2vOqeTvZxkIaXOOlxPyuxSwl47F7m/x5TrTIdj8riLCsIXc3JxP4woxonyfLJ/A61RCuhfHnw3HXtL5+KSiUjP8lvQNV7MpgW1LdiEjeEvFMvGPAVhj8Z5n8QCwAhhyNhf3BINFc15FmiXUL5kzuxjFE//XK9iVZCg+ga8Ql3VocrUKUEh5yXI6xniVfCwLc5VjxiyiaDDOeEE8+SdtULg66gnQgUXflk8LFk/3WqQTwWYXkTxg30/ryoCjnaMeA1b3EkRZjMhU3WUeRm4ws46DfZPKTyFMmzcZsNtIKvzz9LyEpaCgiSuRbJiL9erM/uzFpm+6iaQDFC9yEK/1v2Uc8P9FOAuE/uhLNAVefLPGIFvpXIQLdDmJsL4QOXZYbIB1utsDWzYlKzMrIvbMepp2Uzo4bFqBr8qZPDrZh1g="
  region: us-east-1
  app: SplytDemoApi
  env: SplytDemoApi-env
  bucket_name: splyt-travis-ci-s3
  on:
    branch: master
after_deploy:
- echo "done deploying"

